server:
  port: 8080
  servlet:
    context-path: /

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: classpath:com/jackeyj/erp_dev/entity
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/erp_jssb?characterEncoding=utf-8
    username: root
    password: 123456
  application:
    name: erp-dev
